common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/.cache/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.2

model_args:
  model: "VGG11"

train_args:
  federated_optimizer: "FedNova"
  client_id_list: "[]"
  client_num_in_total: 100 #100
  client_num_per_round: 4 #10
  comm_round: 100 #50
  epochs: 2 #5
  batch_size: 32 #32
  client_optimizer: sgd
  learning_rate: 0.02 #0.001
  weight_decay: 0.0001 #0.0005
#  ci: 1.0
  gmf: 0.0
  mu : 0.0
  momentum: 0.9
  dampening: 0.0
  nesterov: False

validation_args:
  frequency_of_the_test: 2

device_args:
  worker_num: 4
  using_gpu: false

# device_args:
#   using_gpu: false
#   gpu_id: 0

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/.fedml/fedml-client/fedml/logs/ and ~/.fedml/fedml-server/fedml/logs/
  enable_wandb: true
  wandb_key: 63a4dccbf22454ee89c03213ddaba326fa6d7460
  wandb_project: fednova_with_dp
  using_mlops: false
  
dp_args:
  enable_dp: true
  dp_solution_type: nbafl
  epsilon: 0.5
  delta: 0.1
  C: 10
