common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/.cache/fedml_data
  partition_method: "hetero"
  partition_alpha: 1.0

model_args:
  model: "VGG11"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 16
  client_num_per_round: 8  #from 4 to 6
  comm_round: 100 
  epochs: 2 #reduced to 2 from 10
  batch_size: 32
  client_optimizer: sgd
  learning_rate: 0.01 
  weight_decay: 0.0
  gmf: 0.0
  mu : 0.0 #added now
  momentum: 0.0 #added now
  dampening: 0.0
  nesterov: False

validation_args:
  frequency_of_the_test: 2

device_args:
  worker_num: 8
  using_gpu: true
  gpu_mapping_file: config/gpu_mapping.yaml
  gpu_mapping_key: mapping_local


# device_args:
#   using_gpu: false
#   gpu_id: 0

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/.fedml/fedml-client/fedml/logs/ and ~/.fedml/fedml-server/fedml/logs/
  enable_wandb: true
  wandb_key: 63a4dccbf22454ee89c03213ddaba326fa6d7460
  wandb_project: Correct DP-SGD
  run_name: "FedAvg - nm=1, cn=1 (Gaussian)"
  using_mlops: false

dp_args:
  enable_dp_ldp: true
  # epsilon: 1.0
  # mechanism_type: gaussian
  # sensitivity: 1.0
  delta: 0.00001
  clip_norm: 1.0
  noise_multiplier: 1.0
  mechanism_type: DP-SGD-gaussian
