common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "mnist"
  data_cache_dir: ~/.cache/fedml_data
  partition_method: "hetero"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedNova"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 10
  comm_round: 10
  epochs: 20
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.03
  weight_decay: 0.001
  wd: 0.001
  ci: 0
  gmf: 0
  mu : 0
  momentum: 0
  dampening: 0
  nesterov: False

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 4
  using_gpu: false

# device_args:
#   using_gpu: false
#   gpu_id: 0

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/.fedml/fedml-client/fedml/logs/ and ~/.fedml/fedml-server/fedml/logs/
  enable_wandb: true
  wandb_key: 63a4dccbf22454ee89c03213ddaba326fa6d7460
  wandb_project: test_fednova
  run_name: tester
  using_mlops: false
